#!/bin/sh
# --- Aikido local scanner ---
[ -x "/home/salmon/.local/bin/aikido-local-scanner" ] || { echo "Aikido Local Scanner is missing. Find install instructions at https://help.aikido.dev/code-scanning/local-code-scanning/aikido-secrets-pre-commit-hook"; exit 1; }
REPO_ROOT="$(git rev-parse --show-toplevel)"
"/home/salmon/.local/bin/aikido-local-scanner" pre-commit-scan "$REPO_ROOT"
# --- End Aikido local scanner ---

/home/salmon/git/dotfiles/check_git_permissions_match.sh
